#-------------------------------
# Site Settings

title: Jordan Maxwell
description: Jordan Maxwell's Personal Portfolio

menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    #- url: '/about'
    #  title: 'About'
    - title: 'Projects'
      url: '/projects/'
    #- title: 'Blog'
    #  url: '/blog/'

# Call to action button
cta__button__text: Get in touch

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/images/project-eco-10.jpg'


#-------------------------------
# Author Settings

author:
  name: Jordan Maxwell
  title: Hello I’m Jordan Maxwell
  bio: Game Developer & DevOps engineer based in Wisconsin, crafting creative and fun games for desktop and mobile. When I’m not working, I’m probably tinkering with a crazy personal project.
  image: 'https://avatars.githubusercontent.com/u/2001527?v=4'
  avatar: 'https://avatars.githubusercontent.com/u/2001527?v=4'
  button__text: See my projects


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: Latest <span class="text-span">Games</span> and <span class="text-span">Personal Projects</span> # Add a 'text-span' class to highlight text.
  projects__description: A complete collection of all my notable projects and games.


#-------------------------------
# Testimonials Section

testimonial__title: My Happy <span class="text-span">Clients</span> # Add a 'text-span' class to highlight text.
testimonial__enabled: false # Enable or disable the testimonial section

testimonial-items:
  - name: "CRREAM"
    image: "https://static-cdn.jtvnw.net/jtv_user_pictures/e74c8edc-127c-446b-92e4-1d18d96675c0-profile_image-70x70.png"
    designation : "Streamer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Ann Philips"
    image: "/images/client-2.jpg"
    designation : "Designer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Roger Bergson"
    image: "/images/client-3.jpg"
    designation : "CEO, Founder"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."

  - name: "Julie Arnold"
    image: "/images/client-4.jpg"
    designation : "Full stack developer"
    content : "Quamquam id quidem, infinitum est in hac urbe, Ita multo sanguine profuso in laetitia et in victoria est mortuus. Atqui pugnantibus et contrariis consiliisque."


#-------------------------------
# Blog Section

blog__settings:
  blog__title: Recent <span class="text-span">Blog</span> Posts # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: me@jordan-maxwell.com # Add your email for contact form
  contact__title: <span class="text-span">Get</span> in touch # Add a title to your form
  contact__description: Reach out if you have questions about an open source project or looking for a freelance developer! # Add a description to your form


#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Join</span> my mailing list # Add your title
  mailchimp__text: " 'Get inspiration, updates and', 'cool stuff about design!' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text
  mailchimp__enabled: false # Enable or disable the newsletter form


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: thetestgame # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/thetestgame2"}
- {icon: "ion-logo-github", link: "https://github.com/thetestgame"}
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/in/thetestgame"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/channel/UCe3YxaTrVk25oaO1mFSs2cw"}
- {icon: "ion-logo-twitch", link: "https://twitch.tv/thetestgame"}