#
name: Publish website content from Github Issues
on:
  issue_comment:
    types: [created]

# Environment variable constants for this workflow
env:
  GITHUB_ACCOUNT_SITE_OWNER: thetestgame
  GIT_USER_NAME: nxtlabs13@gmail
  GIT_USER_EMAIL: Jordan Maxwell

jobs:
  # Publishes a new website post using the issue command 'publish-post'
  publish-post-from-issue:
    name: Publishes a Github issue as a site post file
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish-post'
    steps:
      - name: Checkout release branch
        uses: actions/checkout@master
        with:
          ref: release

      - name: Create website post file
        if: success() && github.event.issue.user.login == env.GITHUB_ACCOUNT_SITE_OWNER
        run: |
          cat << 'EOF' > $POST_DIRECTORY/${{ github.event.issue.title }}
          ${{ github.event.issue.body }}
          EOF
        env:
          POST_DIRECTORY: '_posts'

      - name: Commit files
        if: success()
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          DEFAULT_COMMIT_MESSAGE: 'New website post created from Github issue'

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

  # Publishes a new website project using the issue command 'publish-project'
  publish-project-from-issue:
    name: Publishes a Github issue as a site project file
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish-project'
    steps:
      - name: Checkout release branch
        uses: actions/checkout@master
        with:
          ref: release

      - name: Create website post file
        if: success() && github.event.issue.user.login == env.GITHUB_ACCOUNT_SITE_OWNER
        run: |
          cat << 'EOF' > $POST_DIRECTORY/${{ github.event.issue.title }}
          ${{ github.event.issue.body }}
          EOF
        env:
          POST_DIRECTORY: '_projects'

      - name: Commit files
        if: success()
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Jordan Maxwell'
          GIT_USER_EMAIL: 'nxtlabs13@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New website project created from Github issue'

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

  # Publishes a new website game using the issue command 'publish-game'
  publish-game-from-issue:
    name: Publishes a Github issue as a site game file
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish-game'
    steps:
      - name: Checkout release branch
        uses: actions/checkout@master
        with:
          ref: release

      - name: Create website post file
        if: success() && github.event.issue.user.login == env.GITHUB_ACCOUNT_SITE_OWNER
        run: |
          cat << 'EOF' > $POST_DIRECTORY/${{ github.event.issue.title }}
          ${{ github.event.issue.body }}
          EOF
        env:
          POST_DIRECTORY: '_games'

      - name: Commit files
        if: success()
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Jordan Maxwell'
          GIT_USER_EMAIL: 'nxtlabs13@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New website project created from Github issue'

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

  # Publishes a new website mod using the issue command 'publish-mod'
  publish-mod-from-issue:
    name: Publishes a Github issue as a site mod file
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish-mod'
    steps:
      - name: Checkout release branch
        uses: actions/checkout@master
        with:
          ref: release

      - name: Create website post file
        if: success() && github.event.issue.user.login == env.GITHUB_ACCOUNT_SITE_OWNER
        run: |
          cat << 'EOF' > $POST_DIRECTORY/${{ github.event.issue.title }}
          ${{ github.event.issue.body }}
          EOF
        env:
          POST_DIRECTORY: '_mods'

      - name: Commit files
        if: success()
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"
          git add --all
          # commit only if there are changes
          if [[ `git status --porcelain` ]]; then
            git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
          fi
        env:
          GIT_USER_NAME: 'Jordan Maxwell'
          GIT_USER_EMAIL: 'nxtlabs13@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New website project created from Github issue'

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release